//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ConsoleApp1 Version: 4.6.6
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:\Users\Артём\RiderProjects\Tests\Tests\Math.g4 by ConsoleApp1 4.6.6

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace ConsoleApp2 {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="MathParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ConsoleApp1", "4.6.6")]
[System.CLSCompliant(false)]
public interface IMathListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="MathParser.start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStart([NotNull] MathParser.StartContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MathParser.start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStart([NotNull] MathParser.StartContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="MathParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] MathParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MathParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] MathParser.StatementContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="MathParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] MathParser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MathParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] MathParser.ExpressionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="MathParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignment([NotNull] MathParser.AssignmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MathParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignment([NotNull] MathParser.AssignmentContext context);
}
} // namespace Tests
